# Basic
title: 沧彧
subtitle: 春天里的油菜花
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">我的githubz主页</a>
description: 学习 思考 进步.
creator: <a href="http://image.baidu.com/search/detail?ct=503316480&z=undefined&tn=baiduimagedetail&ipn=d&word=git&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=undefined&hd=undefined&latest=undefined&copyright=undefined&cs=1804702890,1396280740&os=2361046278,3596843206&simid=0,0&pn=5&rn=1&di=226380&ln=1756&fr=&fmq=1574519700230_R&fm=&ic=undefined&s=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&is=0,0&istype=0&ist=&jit=&bdtype=0&spn=0&pi=0&gsm=0&objurl=http%3A%2F%2Fsnipcart.com%2Fmedia%2F10182%2Fgit-based-content-workflow-github.jpg&rpstart=0&rpnum=0&adpicid=0&force=undefined"</a>

url: "https://github.com/nonoboboq/robust_cyu.github.io.git"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
